[package]
name = "bevy_notify"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app = "0.17.3"
bevy_ecs = "0.17.3"
bevy_reflect = "0.17.3"
src = "0.0.6"

[dev-dependencies]
bevy = { version = "0.17.3", features = ["experimental_bevy_ui_widgets"] }
